### ISSUE TITLE
minor issue

### ISSUE THREAD

**Issue by rcoss** [jonabbey/panda-imap#1]
Line 45 in src/imapd/Makefile should read:
# ESEARCH= -DESEARCH=1  instead of #ESEARCH=1 if it were to be useful when uncommented.

Thanks Jon for putting Mark's panda-imap here.

**Comment by jonabbey** [comment]
On Fri, Jun 14, 2013 at 01:06:12PM -0700, rcoss wrote:
| Line 45 in src/imapd/Makefile should read:
| #ESEARCH= -DESEARCH=1  instead of #ESEARCH=1 if it were to be useful when uncommented.

Of course, I'll see to it.

| Thanks Jon for putting Mark's panda-imap here.

The thanks goes to Mark for maintaining an open license on his fork
even when he was doing it on his own time.

But, my pleasure.

 Jon

## 

---

Jonathan Abbey                                            jonabbey@ganymeta.org
Austin, TX                                             http://www.ganymeta.org/
GPG Key: 50D3B73B at keyserver pgp.mit.edu, http://www.ganymeta.org/homekey.gpg

**Comment by jonabbey** [comment]
Fixed in 9d07ad610ed1756f24def845699ac3a33a7edf71
